### ISSUE TITLE
Catch2 package issue when clone and building

### ISSUE THREAD

**Issue by s0301132** [chronoxor/CppServer#35]
Hi @chronoxor 

There are 2 issues when using the external package `Catch2`:

1: The branch name change from 'master' to 'devel', when python gil clone this package will show can't find this package, I clone the latest 'devel' to modules files to solve this problem.

2: The latest Catch2 package remove the file `single_include`, so when building this project it will show can't find this file when building.

First problem:
```(base) chihungchung@ChideMacBook-Pro CppServer % gil update     
Working path: /Users/chihungchung/Documents/CppServer
Discover git links: /Users/chihungchung/Documents/CppServer/.gitlinks
Running git clone https://github.com/catchorg/Catch2.git branch "master" into /Users/chihungchung/Documents/CppServer/modules/Catch2
Cloning into '/Users/chihungchung/Documents/CppServer/modules/Catch2'...
fatal: Remote branch master not found in upstream origin
Traceback (most recent call last):
  File "/Users/chihungchung/opt/anaconda3/bin/gil.py", line 412, in <module>
    sys.exit(main())
  File "/Users/chihungchung/opt/anaconda3/bin/gil.py", line 401, in main
    context.clone()
  File "/Users/chihungchung/opt/anaconda3/bin/gil.py", line 155, in clone
    self.git_clone(value.path, value.repo, value.branch, args)
  File "/Users/chihungchung/opt/anaconda3/bin/gil.py", line 308, in git_clone
    raise Exception("Failed to run git clone %s branch \"%s\" into %s" % (repo, branch, path))
Exception: Failed to run git clone https://github.com/catchorg/Catch2.git branch "master" into /Users/chihungchung/Documents/CppServer/modules/Catch2
```

Second problem:
![WhatsApp Image 2020-10-28 at 23 41 33](https://user-images.githubusercontent.com/47412725/97463763-0de95780-197b-11eb-8387-2ebd96391bb2.jpeg)

May be I clone the older branch of Catch2 can solve this problem?

**Comment by chronoxor** [comment]
Fixed
